//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace company_management.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class leave_request
    {
        public int id { get; set; }
        public int idUser { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> numberDate { get; set; }
        public string reason { get; set; }
        public string status { get; set; }
    
        public virtual user user { get; set; }
    }
}
