//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace company_management.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class company_managementEntities : DbContext
    {
        public company_managementEntities()
            : base("name=company_managementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kpi> kpis { get; set; }
        public virtual DbSet<leave_request> leave_request { get; set; }
        public virtual DbSet<salary> salaries { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<checkin_checkout> checkin_checkout { get; set; }
    
        [DbFunction("company_managementEntities", "GetTaskStatusPercentage")]
        public virtual IQueryable<GetTaskStatusPercentage_Result> GetTaskStatusPercentage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetTaskStatusPercentage_Result>("[company_managementEntities].[GetTaskStatusPercentage]()");
        }
    }
}
