//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace company_management.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_position
    {
        public int id { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idPosition { get; set; }
    }
}
